project_id = "ldfbpmsnfpmfgxralvsm"

[functions.search-players]
verify_jwt = true

[functions.refresh-player-stats]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.paddle-manage]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.manage-subscription]
verify_jwt = true

[functions.paddle-webhook]
verify_jwt = false

[functions.paddle-portal]
verify_jwt = true
